# Generated by Django 4.2.5 on 2023-09-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicTier',
            fields=[
                ('tier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.tier')),
            ],
            bases=('images.tier',),
        ),
        migrations.CreateModel(
            name='EnterpriseTier',
            fields=[
                ('tier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.tier')),
            ],
            bases=('images.tier',),
        ),
        migrations.CreateModel(
            name='PremiumTier',
            fields=[
                ('tier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.tier')),
            ],
            bases=('images.tier',),
        ),
        migrations.RenameField(
            model_name='tier',
            old_name='thumbnail_sizes',
            new_name='thumbnail_sizes1',
        ),
        migrations.AddField(
            model_name='tier',
            name='thumbnail_sizes2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
