# Generated by Django 4.2.5 on 2023-09-22 18:42

from django.db import migrations, models


def create_tiers(apps, schema_editor):
    Tier = apps.get_model('images', 'Tier')

    basic_tier = Tier.objects.create(
        name="Basic",
        thumbnail_sizes1="200"
    )

    premium_tier = Tier.objects.create(
        name="Premium",
        thumbnail_sizes1="200",
        thumbnail_sizes2="400",
        has_original_link=True
    )

    enterprise_tier = Tier.objects.create(
        name="Enterprise",
        thumbnail_sizes1="200",
        thumbnail_sizes2="400",
        has_original_link=True,
        can_generate_expiring_link=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_tiers),
    ]
