# Generated by Django 4.2.5 on 2023-09-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_basictier_enterprisetier_premiumtier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='thumbnail_sizes1',
            field=models.CharField(blank=True, default='200', max_length=255, null=True),
        ),
    ]
