# Generated by Django 4.2.5 on 2023-09-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_tier_thumbnail_sizes1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='original/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_200px',
            field=models.ImageField(blank=True, null=True, upload_to='200px/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_400px',
            field=models.ImageField(blank=True, null=True, upload_to='400px/'),
        ),
    ]
