# Generated by Django 4.2.5 on 2023-09-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_image_image_file_alter_image_thumbnail_200px_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tier',
            old_name='thumbnail_sizes1',
            new_name='thumbnail_size',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_200px',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_400px',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='thumbnail_sizes2',
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
