# Generated by Django 4.2.5 on 2023-09-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_200px',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_400px',
            field=models.URLField(blank=True, null=True),
        ),
    ]
