# Generated by Django 4.2.5 on 2023-09-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='expiring_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='expiration_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
